steps:
  - name: gradle:7.0.0-jre11
    entrypoint: gradle
    args: [ "build" ]
    dir: 'demo/'
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['init']
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['plan',  '-var-file=input.tfvars']
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['apply', '-auto-approve', '-var-file=input.tfvars']

