steps:
  - name: gradle:6.8.3-jre11
    entrypoint: gradle
    args: [ "build", "--debug"]
    dir: 'demo/'
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['init']
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['plan',  '-var-file=input.tfvars']
  - name: 'gcr.io/${PROJECT_ID}/terraform'
    args: ['apply', '-auto-approve', '-var-file=input.tfvars']

